version: "3.8"

services:
  ca-web:
    build: .
    volumes:
      - ./site/:/var/www/html
    ports:
      - "5000:80"
    environment:
      DB_HOST: converterapp-db.xxxxx.us-east-1.rds.amazonaws.com
      DB_NAME: converterApp
      DB_USER: converteruser
      DB_PASS: your_db_password